In [1]:
import kagglehub
import pandas as pd
import numpy as np
# Download latest version
path = kagglehub.dataset_download("laotse/credit-risk-dataset")

print("Path to dataset files:", path)

G:\facultate\anul 3 sem 2\Practica de specialiate\S2-Data-Processing-Exploratory-Data-Analysis\.venv3.12\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\Petrisor\.cache\kagglehub\datasets\laotse\credit-risk-dataset\versions\1

In [2]:
path = "C:\\Users\\Petrisor\\.cache\\kagglehub\\datasets\\laotse\\credit-risk-dataset\\versions\\1\\credit_risk_dataset.csv"

In [3]:
df =pd.read_csv(path)
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

In [5]:
df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

Stergerea lniilor duplicate

In [6]:
df.drop_duplicates()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [24]:
df.head(50)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
5,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
6,26,77100,RENT,8.0,EDUCATION,B,35000,12.42,1,0.45,N,3
7,24,78956,RENT,5.0,MEDICAL,B,35000,11.11,1,0.44,N,4
8,24,83000,RENT,8.0,PERSONAL,A,35000,8.90,1,0.42,N,2
9,21,10000,OWN,6.0,VENTURE,D,1600,14.74,1,0.16,N,3
10,22,85000,RENT,6.0,VENTURE,B,35000,10.37,1,0.41,N,4
11,21,10000,OWN,2.0,HOMEIMPROVEMENT,A,4500,8.63,1,0.45,N,2
12,23,95000,RENT,2.0,VENTURE,A,35000,7.90,1,0.37,N,2
13,26,108160,RENT,4.0,EDUCATION,E,35000,18.39,1,0.32,N,4
14,23,115000,RENT,2.0,EDUCATION,A,35000,7.90,0,0.30,N,4
15,23,500000,MORTGAGE,7.0,DEBTCONSOLIDATION,B,30000,10.65,0,0.06,N,3
16,23,120000,RENT,0.0,EDUCATION,A,35000,7.90,0,0.29,N,4
17,23,92111,RENT,7.0,MEDICAL,F,35000,20.25,1,0.32,N,4
18,23,113000,RENT,8.0,DEBTCONSOLIDATION,D,35000,18.25,1,0.31,N,4
19,24,10800,MORTGAGE,8.0,EDUCATION,B,1750,10.99,1,0.16,N,2
20,25,162500,RENT,2.0,VENTURE,A,35000,7.49,0,0.22,N,4
21,25,137000,RENT,9.0,PERSONAL,E,34800,16.77,0,0.25,Y,2
22,22,65000,RENT,4.0,EDUCATION,D,34000,17.58,1,0.52,N,4
23,24,10980,OWN,0.0,PERSONAL,A,1500,7.29,0,0.14,N,3
24,22,80000,RENT,3.0,PERSONAL,D,33950,14.54,1,0.42,Y,4
25,24,67746,RENT,8.0,HOMEIMPROVEMENT,C,33000,12.68,1,0.49,N,3
26,21,11000,MORTGAGE,3.0,VENTURE,E,4575,17.74,1,0.42,Y,3
27,23,11000,OWN,0.0,PERSONAL,A,1400,9.32,0,0.13,N,3
28,24,65000,RENT,6.0,HOMEIMPROVEMENT,B,32500,9.99,1,0.50,N,3
29,21,11389,OTHER,5.0,EDUCATION,C,4000,12.84,1,0.35,Y,2
30,21,11520,OWN,5.0,MEDICAL,B,2000,11.12,1,0.17,N,3
31,25,120000,RENT,2.0,VENTURE,A,32000,6.62,0,0.27,N,2
32,26,95000,RENT,7.0,HOMEIMPROVEMENT,C,31050,14.17,1,0.33,Y,3
33,25,306000,RENT,2.0,DEBTCONSOLIDATION,C,24250,13.85,0,0.08,N,3
34,26,300000,MORTGAGE,10.0,MEDICAL,C,7800,13.49,0,0.03,N,4
35,21,12000,OWN,5.0,EDUCATION,A,2500,7.51,1,0.21,N,4
36,22,48000,RENT,1.0,EDUCATION,E,30000,18.39,1,0.63,N,2
37,24,64000,RENT,8.0,DEBTCONSOLIDATION,D,30000,14.54,1,0.47,Y,3
38,25,75000,RENT,4.0,HOMEIMPROVEMENT,D,30000,16.89,1,0.40,Y,4
39,23,71500,RENT,3.0,DEBTCONSOLIDATION,D,30000,NaN,1,0.42,N,4
40,26,62050,RENT,6.0,MEDICAL,E,30000,17.99,1,0.41,N,2
41,24,12000,OWN,4.0,VENTURE,B,2500,12.69,1,0.21,N,3
42,26,300000,MORTGAGE,10.0,VENTURE,A,20000,7.88,0,0.07,N,4
43,23,300000,OWN,1.0,EDUCATION,F,24250,19.41,0,0.08,Y,2
44,26,300000,OWN,9.0,HOMEIMPROVEMENT,B,10000,10.38,0,0.03,N,4
45,26,300000,MORTGAGE,0.0,EDUCATION,D,25000,15.33,0,0.08,N,3
46,25,300000,MORTGAGE,9.0,HOMEIMPROVEMENT,E,18000,16.45,0,0.06,N,3
47,26,80690,RENT,8.0,PERSONAL,A,30000,7.49,1,0.37,N,3
48,22,66300,RENT,4.0,MEDICAL,B,30000,12.69,1,0.38,N,3
49,26,89028,RENT,0.0,DEBTCONSOLIDATION,A,30000,6.62,1,0.34,N,3

In [28]:
df.sort_values('person_age').head(50)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
7748,20,34800,RENT,3.0,MEDICAL,C,7000,13.61,0,0.20,Y,2
1313,20,64000,RENT,3.0,VENTURE,D,16000,15.31,1,0.25,Y,4
16339,20,188004,MORTGAGE,4.0,PERSONAL,A,2000,8.59,0,0.01,N,2
9926,20,65000,MORTGAGE,4.0,EDUCATION,B,4800,9.99,0,0.07,N,2
15830,20,188004,MORTGAGE,4.0,EDUCATION,A,2000,8.59,0,0.01,N,4
7327,20,42000,RENT,4.0,VENTURE,B,6500,11.71,0,0.15,N,2
15417,20,135000,MORTGAGE,1.0,VENTURE,C,15000,15.96,0,0.11,Y,2
14827,20,115731,MORTGAGE,4.0,DEBTCONSOLIDATION,B,9625,10.74,0,0.08,N,3
17196,20,65000,MORTGAGE,4.0,VENTURE,B,4800,9.99,0,0.07,N,4
13918,20,98000,MORTGAGE,4.0,EDUCATION,D,24250,NaN,0,0.25,N,4
3851,20,32652,MORTGAGE,0.0,PERSONAL,D,6000,14.61,1,0.18,N,4
5648,20,94000,RENT,4.0,EDUCATION,D,5000,16.02,0,0.05,N,3
11889,20,77000,MORTGAGE,4.0,VENTURE,A,6000,8.00,0,0.08,N,2
11902,20,77052,MORTGAGE,4.0,EDUCATION,B,24250,11.36,0,0.31,N,2
12943,20,85920,MORTGAGE,3.0,DEBTCONSOLIDATION,A,12000,8.49,0,0.14,N,2
1325,21,20000,RENT,2.0,DEBTCONSOLIDATION,C,1000,14.26,0,0.05,Y,2
1351,21,30000,RENT,0.0,EDUCATION,B,1000,10.99,0,0.03,N,4
16458,21,60000,RENT,2.0,VENTURE,A,5000,8.49,0,0.08,N,2
1339,21,26000,MORTGAGE,5.0,MEDICAL,D,14500,14.61,1,0.56,Y,2
1335,21,24960,RENT,0.0,EDUCATION,C,1000,13.98,0,0.04,N,4
1333,21,24000,RENT,0.0,MEDICAL,B,1000,10.99,1,0.04,N,2
7764,21,29000,RENT,5.0,MEDICAL,D,7000,12.61,1,0.24,Y,2
1297,21,65000,RENT,5.0,PERSONAL,B,16000,9.91,0,0.25,N,3
7722,21,32000,RENT,3.0,VENTURE,B,7000,11.49,0,0.22,N,2
7716,21,30600,RENT,NaN,DEBTCONSOLIDATION,A,7000,7.29,0,0.23,N,2
9761,21,20000,RENT,2.0,MEDICAL,A,9000,7.51,1,0.45,N,4
16440,21,26000,RENT,5.0,DEBTCONSOLIDATION,A,6000,7.49,0,0.23,N,2
1363,21,33388,RENT,3.0,EDUCATION,B,1000,10.99,0,0.03,N,2
1354,21,30000,RENT,0.0,DEBTCONSOLIDATION,A,1000,NaN,0,0.03,N,3
7703,21,30000,RENT,2.0,PERSONAL,B,7000,10.99,1,0.23,N,2
9776,21,26785,RENT,6.0,MEDICAL,A,9000,7.90,1,0.34,N,4
4882,21,38000,RENT,0.0,EDUCATION,C,5000,NaN,0,0.13,Y,4
4909,21,33996,RENT,3.0,PERSONAL,B,5000,9.25,1,0.15,N,3
12666,21,84000,MORTGAGE,5.0,DEBTCONSOLIDATION,B,10000,12.53,0,0.12,N,4
4892,21,38400,RENT,5.0,PERSONAL,B,5000,10.59,0,0.13,N,4
12628,21,84000,MORTGAGE,5.0,EDUCATION,B,2500,9.99,0,0.03,N,4
4926,21,40000,RENT,3.0,VENTURE,B,5000,9.25,0,0.13,N,4
77,21,12000,OWN,0.0,PERSONAL,C,4200,13.48,1,0.35,Y,4
72,21,12000,OWN,6.0,EDUCATION,C,3000,13.61,1,0.25,Y,3
17767,21,29004,RENT,5.0,PERSONAL,C,11000,14.22,1,0.38,Y,4
26,21,11000,MORTGAGE,3.0,VENTURE,E,4575,17.74,1,0.42,Y,3
60,21,131000,RENT,0.0,VENTURE,A,30000,5.99,0,0.23,N,4
29,21,11389,OTHER,5.0,EDUCATION,C,4000,12.84,1,0.35,Y,2
5,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
9,21,10000,OWN,6.0,VENTURE,D,1600,14.74,1,0.16,N,3
30,21,11520,OWN,5.0,MEDICAL,B,2000,11.12,1,0.17,N,3
1329,21,26000,OWN,5.0,EDUCATION,A,6000,5.79,0,0.23,N,2
4799,21,33600,RENT,4.0,EDUCATION,C,5000,13.49,0,0.15,N,3
4794,21,33000,RENT,5.0,EDUCATION,C,5000,12.84,0,0.15,N,2
12602,21,24996,RENT,0.0,DEBTCONSOLIDATION,B,3000,11.49,0,0.12,N,3

In [92]:
nan_cells = pd.isna(df["person_emp_length"])

In [93]:
nan_cells

0        False
1        False
2        False
3        False
4        False
         ...
32576    False
32577    False
32578    False
32579    False
32580    False
Name: person_emp_length, Length: 32581, dtype: bool

In [94]:
nan_cells.loc[nan_cells ==True]

105      True
222      True
379      True
407      True
408      True
         ...
32285    True
32328    True
32360    True
32453    True
32471    True
Name: person_emp_length, Length: 895, dtype: bool

In [86]:
missing_data = df[nan_cells]

In [9]:
df.dropna(axis=1)

,person_age,person_income,person_home_ownership,loan_intent,loan_grade,loan_amnt,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,PERSONAL,D,35000,1,0.59,Y,3
1,21,9600,OWN,EDUCATION,B,1000,0,0.10,N,2
2,25,9600,MORTGAGE,MEDICAL,C,5500,1,0.57,N,3
3,23,65500,RENT,MEDICAL,C,35000,1,0.53,N,2
4,24,54400,RENT,MEDICAL,C,35000,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,PERSONAL,C,5800,0,0.11,N,30
32577,54,120000,MORTGAGE,PERSONAL,A,17625,0,0.15,N,19
32578,65,76000,RENT,HOMEIMPROVEMENT,B,35000,1,0.46,N,28
32579,56,150000,MORTGAGE,PERSONAL,B,15000,0,0.10,N,26
32580,66,42000,RENT,MEDICAL,B,6475,0,0.15,N,30

In [12]:
sns.distplot(df["person_income"])

ModuleNotFoundError: No module named 'seaborn'